### ISSUE TITLE
Mathilda drops fairy dust when speech bubble hits plant life

### ISSUE THREAD

**Issue by flyingpianos** [IBwWG/mathildagame-bugs#103]
Gathered fairy dust by high fiving some sea life, and while the speech bubble (e.g. "8 more!") was still on the screen, it "ran into" the next plant life at the top of the screen causing Mathilda to drop her fairy dust.  I had not tapped, pressed, or held down any buttons after getting the initial high five.  
This was in Easy mode.  Was able to repeat several times.

**Comment by IBwWG** [comment]
Thanks for the report, but I think you're misunderstanding the premise, because the bubbles do not have collision checks.  You _want_ to collide with everything.  It's when you miss a high-five that she drops.  It's interesting that you were able to repeat it, but I believe it's a coincidence: what's actually happening is that elsewhere on the screen you have gone by something without high-fiving it.  Can you confirm?

**Comment by IBwWG** [comment]
Well, reopen if need be.
