### ISSUE TITLE
Involuntary left & right movement of Catfish 

### ISSUE THREAD

**Issue by flyingpianos** [IBwWG/mathildagame-bugs#106]
When bouncing the Catfish on the trampoline, specifically when under 8 feet, it often involuntarily would move itself toward the hoops.  (In other words, if he was on the left trampoline, he would start moving to the right in mid-air, if still under 8 feet...)

**Comment by IBwWG** [comment]
This is intentional, although it shouldn't be only when under 8 feet, it's actually only when above the bottom of the bottommost ring (so it doesn't try to switch sides if you're just hanging out on the trampoline.)  I made the switching automatic to simplify the controls, and because you never really lose anything from a failed switch, so why not try every time?
